name: Pipeline CI/CD Innovatech Despacho

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de la imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest

      - name: Despliegue en EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest
            docker stop backend-despacho || true
            docker rm backend-despacho || true
            docker run -d --name backend-despacho -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/backend-despacho:latest
            docker image prune -f
